# -*- coding: utf-8 -*-
"""Hands on LLM book Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TyrY6I2pBpFOWslMHLznlORk6VrdyHIB

#Generating my first text

1. Loading the model and tokenizer

  These are the different available good models from hugging face,
*   LLAMA = "meta-llama/Llama-3.2-1B-Instruct"
*   PHI = "microsoft/Phi-4-mini-instruct"
*   GEMMA = "google/gemma-3-270m-it"
*   QWEN = "Qwen/Qwen3-4B-Instruct-2507"
*   DEEPSEEK = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"

*   ##Inorder to use these models you need to have a hugging face login token
"""

from google.colab import userdata
from huggingface_hub import login
hf_token = userdata.get('Murali')
login(hf_token, add_to_git_credential=True)

LLAMA = "meta-llama/Llama-3.2-1B-Instruct"
PHI = "microsoft/Phi-4-mini-instruct"
GEMMA = "google/gemma-3-270m-it"
QWEN = "Qwen/Qwen3-4B-Instruct-2507"
DEEPSEEK = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"

from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained(GEMMA,device_map = "auto", torch_dtype="auto")
tokenizer = AutoTokenizer.from_pretrained(GEMMA)

"""##Now we create a pipeline, so that we have the model, tokenizer and text generation process in a single function"""

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model = model,
    tokenizer = tokenizer,
    return_full_text = False, # this means the prompt will not be returned. Just the output is returned.
    max_new_tokens=500, # to avoid unecessary lengthy text generation
    do_sample = False # picks only most probable next word, instead of sampling between next probable tokens
)

"""#Now we create a prompt or query that we wish to ask the model"""

messages = [{"role":"system", "content":"you are a helpful assistant"},
            {"role":"user", "content": "what is llama?"}]

"""#Now we call the pipeline/generate function with our messages"""

output = generator(messages)

print(output) # this will give response as list of dictionaries

generated_text = output[0]['generated_text'] # we access only the response this way
print(generated_text)

"""#Now we see tokenization.


*   we first declare our prompt
*   then we tokenize the prompt
*   then pass these tokens to the model




"""

prompt = "Write an email apologizing to sarah for tragic gardening mishap.Explain how it happened"

input_ids = tokenizer(prompt, return_tensors="pt").to("cuda") # this gives us a dictionary as output

print(input_ids)

"""##we can visualize these input token id's using decode method"""

print(tokenizer.decode(input_ids['input_ids']))

"""##The output of tokenizer is a dictionary like object(a Batchencoding object) that contains key like 'input_ids' and 'attention_mask'.


*   Bute the generate() function takes only tensors as input, therefore we need to provide the inputs this way.
```python
*   model.generate(
    input_ids=input_ids['input_ids'],
    attention_mask=input_ids['attention_mask'],
    max_new_tokens=20
)
```


*   A cleaner way is using the ** operator




    


"""

mail_output = model.generate(**input_ids, max_new_tokens = 100)

print(mail_output)

"""##we can see that now the output generated is a bunch of tokenid's.


*   Therefore we need to convert them again into tokens using **decode** method

"""

response = tokenizer.decode(mail_output) #This will give a list containing a string, which is our output

response

response[0] # the markdown function need only text not list so we give it this response[0]

"""##If we want to display the output in a better way we use python library *IPython.display*"""

from IPython.display import Markdown, display
display(Markdown(response[0]))

"""##Now we check the same thing for PHI3 mini"""

phi3_model = AutoModelForCausalLM.from_pretrained("microsoft/phi-3-mini-4k-instruct",
                                                  device_map = "auto",
                                                  torch_dtype = "auto")

phi3_tokenizer = AutoTokenizer.from_pretrained("microsoft/phi-3-mini-4k-instruct")

input_ids = phi3_tokenizer(prompt, return_tensors="pt").to("cuda")

print(input_ids)